Repository notaryproject/notaryproject.dev, pull requests merged in 2023-03, with the labels that each got.

#152 doc: add notary fuzzing security audit blog
  content/en/blog/2023/notary-completes-fuzzing-security-audit.md
Labels: documentation

#144 updated CLI install for RC3 and relocated directory structure doc to …
  content/en/docs/concepts/directory-structure.md
  content/en/docs/how-to/notation-config-file.md
  content/en/docs/installation/cli.md
  layouts/partials/banner.html
Labels: documentation, review

#153 added uninstall instructions
  content/en/docs/installation/cli.md
  content/en/docs/installation/uninstall.md
  content/en/docs/quickstart.md
Labels: review

#149 add how-to for authenticating with registries
  content/en/docs/how-to/registry-authentication.md
Labels: documentation, review
