Repository notaryproject/notaryproject.dev, pull requests merged in 2023-11, with the labels that each got.

#295 Updated README file
  README.md
  static/Notary_project_logo.png
Labels: Stale

#336 expand on the trust policy and trust store concepts
  content/en/docs/user-guides/how-to/directory-structure.md
Labels: review

#367 chore: fix broken links
  content/en/_index.html
  content/en/blog/2022/oras-oci-artifacts-notation-signatures.md
  content/en/blog/2023/announcing-major-release.md
  content/en/blog/2023/announcing-notation-rc6.md
  content/en/blog/2023/notation-completes-security-audit.md
  content/en/community/_index.md
Labels: review

#357 chore: remove Docker Hub and add Harbor to the adoption section
  content/en/_index.html
  static/harbor_logo.svg
Labels: review

#124 doc: add adopter list
  content/en/docs/adopters.md
Labels: documentation, review
